# Vault Survival dedicated staff sandbox
accepts-transfers=true
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
difficulty=normal
enable-command-block=true
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=true
force-gamemode=false
gamemode=creative
generate-structures=true
hardcore=false
level-name=staff_test
level-seed=
level-type=minecraft:normal
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=Vault Survival - Isolated Staff Sandbox
online-mode=true
player-idle-timeout=0
pvp=true
rate-limit=0
server-ip=
server-port=25566
simulation-distance=10
spawn-protection=0
sync-chunk-writes=true
view-distance=10
white-list=true

