package com.vaultsurvival.plugin.districts;

import com.vaultsurvival.plugin.core.DatabaseManager;
import java.sql.*;
import java.util.*;
import java.util.concurrent.CompletableFuture;

public final class DistrictFoundingRepository{
    private final DatabaseManager database;
    public DistrictFoundingRepository(DatabaseManager database){this.database=database;}
    public CompletableFuture<DistrictFoundingPetition> create(UUID founder,String name,long expiresAt,String idempotency){return database.write(c->{UUID petition=UUID.randomUUID();long now=System.currentTimeMillis();try(PreparedStatement p=c.prepareStatement("INSERT INTO district_founding_petitions(petition_uuid,founder_uuid,district_name,status,created_at,expires_at,founding_source,idempotency_key) VALUES(?,?,?,'DRAFT',?,?, 'PLAYER_CLERK',?)")){p.setString(1,petition.toString());p.setString(2,founder.toString());p.setString(3,name);p.setLong(4,now);p.setLong(5,expiresAt);p.setString(6,idempotency);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("INSERT INTO district_founding_participants(petition_uuid,player_uuid,role,status,invited_at,responded_at) VALUES(?,?,'MAYOR','ACCEPTED',?,?)")){p.setString(1,petition.toString());p.setString(2,founder.toString());p.setLong(3,now);p.setLong(4,now);p.executeUpdate();}return load(c,petition);});}
    public CompletableFuture<Optional<DistrictFoundingPetition>> byFounder(UUID founder){return database.read(c->{try(PreparedStatement p=c.prepareStatement("SELECT petition_uuid FROM district_founding_petitions WHERE founder_uuid=? AND status IN ('DRAFT','READY') AND expires_at>? ORDER BY created_at DESC LIMIT 1")){p.setString(1,founder.toString());p.setLong(2,System.currentTimeMillis());try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(load(c,UUID.fromString(r.getString(1)))):Optional.empty();}}});}
    public CompletableFuture<List<DistrictFoundingPetition>> invitations(UUID player){return database.read(c->{List<DistrictFoundingPetition> out=new ArrayList<>();try(PreparedStatement p=c.prepareStatement("SELECT petition_uuid FROM district_founding_participants WHERE player_uuid=? AND status='INVITED'")){p.setString(1,player.toString());try(ResultSet r=p.executeQuery()){while(r.next())out.add(load(c,UUID.fromString(r.getString(1))));}}return List.copyOf(out);});}
    public CompletableFuture<DistrictFoundingPetition> invite(UUID petition,UUID founder,UUID invited,DistrictData.DistrictRole role){return database.write(c->{assertFounder(c,petition,founder);if(founder.equals(invited))throw new IllegalArgumentException("Founder is already accepted");try(PreparedStatement p=c.prepareStatement("INSERT INTO district_founding_participants(petition_uuid,player_uuid,role,status,invited_at) VALUES(?,?,?,'INVITED',?) ON CONFLICT(petition_uuid,player_uuid) DO UPDATE SET role=excluded.role,status='INVITED',invited_at=excluded.invited_at,responded_at=NULL")){p.setString(1,petition.toString());p.setString(2,invited.toString());p.setString(3,role.name());p.setLong(4,System.currentTimeMillis());p.executeUpdate();}return load(c,petition);});}
    public CompletableFuture<DistrictFoundingPetition> respond(UUID petition,UUID player,boolean accept){return database.write(c->{try(PreparedStatement p=c.prepareStatement("UPDATE district_founding_participants SET status=?,responded_at=? WHERE petition_uuid=? AND player_uuid=? AND status='INVITED'")){p.setString(1,accept?"ACCEPTED":"DECLINED");p.setLong(2,System.currentTimeMillis());p.setString(3,petition.toString());p.setString(4,player.toString());if(p.executeUpdate()!=1)throw new IllegalStateException("Invitation is no longer pending");}return load(c,petition);});}
    public CompletableFuture<DistrictFoundingPetition> attachClaim(UUID petition,UUID founder,DistrictData.BlockClaim claim,UUID contract){return database.write(c->{assertFounder(c,petition,founder);try(PreparedStatement p=c.prepareStatement("UPDATE district_founding_petitions SET claim_world=?,claim_min_x=?,claim_min_z=?,claim_max_x=?,claim_max_z=?,contract_uuid=?,status='READY' WHERE petition_uuid=?")){p.setString(1,claim.worldName());p.setInt(2,claim.minBlockX());p.setInt(3,claim.minBlockZ());p.setInt(4,claim.maxBlockX());p.setInt(5,claim.maxBlockZ());p.setString(6,contract.toString());p.setString(7,petition.toString());p.executeUpdate();}return load(c,petition);});}
    public CompletableFuture<Submitted> submit(UUID petition,UUID founder){return database.write(c->{DistrictFoundingPetition value=load(c,petition);if(!value.founderUuid().equals(founder))throw new SecurityException("Only the founder may submit");if(value.expiresAt()<System.currentTimeMillis()||value.claim()==null||value.contractUuid()==null||value.acceptedCount()<3)throw new IllegalStateException("Petition requirements are incomplete");try(PreparedStatement exists=c.prepareStatement("SELECT 1 FROM districts WHERE lower(name)=lower(?) AND status!='DISBANDED'")){exists.setString(1,value.districtName());try(ResultSet r=exists.executeQuery()){if(r.next())throw new IllegalStateException("District name is no longer available");}}int districtId;try(PreparedStatement p=c.prepareStatement("INSERT INTO districts(name,founder_uuid,world,center_x,center_z,status,founding_source) VALUES(?,?,?,?,?,'APPLICATION','PLAYER_CLERK')",Statement.RETURN_GENERATED_KEYS)){p.setString(1,value.districtName());p.setString(2,founder.toString());p.setString(3,value.claim().worldName());p.setInt(4,value.claim().centerBlockX());p.setInt(5,value.claim().centerBlockZ());p.executeUpdate();try(ResultSet keys=p.getGeneratedKeys()){if(!keys.next())throw new SQLException("No district id generated");districtId=keys.getInt(1);}}
        for(var participant:value.participants().values())if(participant.status()==DistrictFoundingPetition.ParticipantStatus.ACCEPTED){DistrictData.DistrictRole role=participant.playerUuid().equals(founder)?DistrictData.DistrictRole.MAYOR:DistrictData.DistrictRole.MEMBER;try(PreparedStatement p=c.prepareStatement("INSERT INTO district_members(district_id,player_uuid,role) VALUES(?,?,?)")){p.setInt(1,districtId);p.setString(2,participant.playerUuid().toString());p.setString(3,role.name());p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("INSERT OR IGNORE INTO district_member_roles(district_id,player_uuid,role) VALUES(?,?,?)")){p.setInt(1,districtId);p.setString(2,participant.playerUuid().toString());p.setString(3,role.name());p.executeUpdate();}}
        DistrictData.BlockClaim claim=value.claim();try(PreparedStatement p=c.prepareStatement("INSERT INTO district_claims(district_id,world,min_chunk_x,min_chunk_z,max_chunk_x,max_chunk_z,min_block_x,min_block_z,max_block_x,max_block_z) VALUES(?,?,?,?,?,?,?,?,?,?)")){p.setInt(1,districtId);p.setString(2,claim.worldName());p.setInt(3,Math.floorDiv(claim.minBlockX(),16));p.setInt(4,Math.floorDiv(claim.minBlockZ(),16));p.setInt(5,Math.floorDiv(claim.maxBlockX(),16));p.setInt(6,Math.floorDiv(claim.maxBlockZ(),16));p.setInt(7,claim.minBlockX());p.setInt(8,claim.minBlockZ());p.setInt(9,claim.maxBlockX());p.setInt(10,claim.maxBlockZ());p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("UPDATE district_founding_petitions SET status='SUBMITTED',submitted_at=? WHERE petition_uuid=? AND status='READY'")){p.setLong(1,System.currentTimeMillis());p.setString(2,petition.toString());if(p.executeUpdate()!=1)throw new IllegalStateException("Petition was already submitted");}return new Submitted(districtId,value);});}
    private void assertFounder(Connection c,UUID petition,UUID founder)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT 1 FROM district_founding_petitions WHERE petition_uuid=? AND founder_uuid=? AND status IN ('DRAFT','READY') AND expires_at>?")){p.setString(1,petition.toString());p.setString(2,founder.toString());p.setLong(3,System.currentTimeMillis());try(ResultSet r=p.executeQuery()){if(!r.next())throw new IllegalStateException("Founding petition is unavailable");}}}
    private DistrictFoundingPetition load(Connection c,UUID petition)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT * FROM district_founding_petitions WHERE petition_uuid=?")){p.setString(1,petition.toString());try(ResultSet r=p.executeQuery()){if(!r.next())throw new IllegalStateException("Founding petition not found");String world=r.getString("claim_world");DistrictData.BlockClaim claim=world==null?null:new DistrictData.BlockClaim(world,r.getInt("claim_min_x"),r.getInt("claim_min_z"),r.getInt("claim_max_x"),r.getInt("claim_max_z"));String contract=r.getString("contract_uuid");Map<UUID,DistrictFoundingPetition.Participant> members=new LinkedHashMap<>();try(PreparedStatement m=c.prepareStatement("SELECT player_uuid,role,status FROM district_founding_participants WHERE petition_uuid=? ORDER BY invited_at")){m.setString(1,petition.toString());try(ResultSet rows=m.executeQuery()){while(rows.next()){UUID id=UUID.fromString(rows.getString(1));members.put(id,new DistrictFoundingPetition.Participant(id,DistrictData.DistrictRole.valueOf(rows.getString(2)),DistrictFoundingPetition.ParticipantStatus.valueOf(rows.getString(3))));}}}return new DistrictFoundingPetition(petition,UUID.fromString(r.getString("founder_uuid")),r.getString("district_name"),r.getString("status"),claim,contract==null?null:UUID.fromString(contract),r.getLong("created_at"),r.getLong("expires_at"),members);}}}
    public record Submitted(int districtId,DistrictFoundingPetition petition){}
}
