package com.vaultsurvival.plugin.districts;

import com.vaultsurvival.plugin.VaultSurvivalPlugin;
import com.vaultsurvival.plugin.core.MessageFormatter;
import com.vaultsurvival.plugin.currency.CurrencyService;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import java.sql.*;
import java.util.List;
import org.bukkit.Bukkit;

/** Persistent, capped district contribution and project foundation. */
public final class DistrictDevelopmentService {
    public record ProjectResult(boolean success, String message, int projectId) { }
    private static final long DAILY_PLAYER_CAP = 10_000;
    private final VaultSurvivalPlugin plugin; private final DistrictService districts; private final CurrencyService cash; private final MessageFormatter fmt; private int maintenanceTask=-1;
    public DistrictDevelopmentService(VaultSurvivalPlugin plugin) { this.plugin=plugin; districts=plugin.getServiceRegistry().get(DistrictService.class); cash=plugin.getServiceRegistry().get(CurrencyService.class); fmt=plugin.getMessageFormatter(); }
    public boolean handle(Player player, String command, String[] args) {
        DistrictData.District district=districts.getPlayerDistrict(player.getUniqueId());
        if(district==null){ player.sendMessage(fmt.error("You are not in a district.")); return true; }
        return switch(command){ case "development" -> { report(player,district); yield true; } case "projects" -> { projects(player,district); yield true; } case "maintenance" -> { maintenance(player,district); yield true; } case "contributors" -> { contributors(player,district); yield true; } case "project" -> project(player,district,args); default -> false; };
    }
    public void startMaintenanceScheduler(){if(maintenanceTask!=-1)return;maintenanceTask=Bukkit.getScheduler().scheduleSyncRepeatingTask(plugin,()->districts.getAllDistricts().stream().filter(d->d.getStatus()==DistrictData.DistrictStatus.ACTIVE).forEach(this::refreshMaintenance),20L*60L,20L*60L*60L);}
    public void stopMaintenanceScheduler(){if(maintenanceTask!=-1){Bukkit.getScheduler().cancelTask(maintenanceTask);maintenanceTask=-1;}}
    public ProjectResult createProject(Player player,String type,long cashRequired,int itemsRequired){DistrictData.District d=districts.getPlayerDistrict(player.getUniqueId());if(d==null)return new ProjectResult(false,"You are not in a district.",-1);if(!districts.canManageDevelopment(player.getUniqueId(),d)||dormant(d)||maintenanceSuspended(d))return new ProjectResult(false,"Your role, district activity, or maintenance state cannot create upgrades.",-1);if(type==null||!type.matches("[A-Z0-9_]{3,40}")||cashRequired<1||itemsRequired<1)return new ProjectResult(false,"Choose a valid project type and positive requirements.",-1);try{double scale=requirementScale(d);long cashScaled=Math.max(1,(long)(cashRequired*scale));int itemsScaled=Math.max(1,(int)(itemsRequired*scale));try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement("INSERT INTO district_projects(district_id,type,category,status,cash_required,item_required,created_by,created_at) VALUES(?,?,?,'ACTIVE',?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){s.setInt(1,d.getId());s.setString(2,type);s.setString(3,category(type));s.setLong(4,cashScaled);s.setInt(5,itemsScaled);s.setString(6,player.getUniqueId().toString());s.setLong(7,System.currentTimeMillis());s.executeUpdate();ResultSet keys=s.getGeneratedKeys();int id=keys.next()?keys.getInt(1):-1;audit(player,"PROJECT_CREATE",d,"project="+id+" type="+type+" scale="+scale);return new ProjectResult(true,"Project #"+id+" created. Cash: "+cashScaled+", items: "+itemsScaled+".",id);}}catch(Exception e){return new ProjectResult(false,"Project could not be created.",-1);}}
    private boolean project(Player p,DistrictData.District d,String[] a){ if(a.length<2){p.sendMessage(fmt.error("Usage: /district project <create|contribute|list|info|pause|resume|support> ..."));return true;} if(a[1].equalsIgnoreCase("list")){projects(p,d);return true;} if(a[1].equalsIgnoreCase("info")){if(a.length<3){p.sendMessage(fmt.error("Usage: /district project info <id>"));return true;}projectInfo(p,d,parse(a[2]));return true;} if(a[1].equalsIgnoreCase("pause")||a[1].equalsIgnoreCase("resume")){if(a.length<3||!districts.canManageDevelopment(p.getUniqueId(),d)){p.sendMessage(fmt.error("Requires project management role and project id."));return true;}try{plugin.getDatabase().executeUpdate("UPDATE district_projects SET status=? WHERE id=? AND district_id=?",a[1].equalsIgnoreCase("pause")?"PAUSED":"ACTIVE",parse(a[2]),d.getId());audit(p,"PROJECT_"+a[1].toUpperCase(),d,"project="+a[2]);p.sendMessage(fmt.success("Project updated."));}catch(Exception e){p.sendMessage(fmt.error("Project update failed."));}return true;} if(a[1].equalsIgnoreCase("create")){if(!districts.canManageDevelopment(p.getUniqueId(),d)||dormant(d)||maintenanceSuspended(d)){p.sendMessage(fmt.error("Your role, district activity, or maintenance state cannot create upgrades."));return true;} if(a.length<5){p.sendMessage(fmt.error("Usage: /district project create <type> <cashRequired> <itemsRequired>"));return true;} try{double scale=requirementScale(d);plugin.getDatabase().executeUpdate("INSERT INTO district_projects (district_id,type,category,status,cash_required,item_required,created_by,created_at) VALUES (?,?,?,'ACTIVE',?,?,?,?)",d.getId(),a[2],category(a[2]),Math.max(1,(long)(Long.parseLong(a[3])*scale)),Math.max(1,(int)(Integer.parseInt(a[4])*scale)),p.getUniqueId().toString(),System.currentTimeMillis()); audit(p,"PROJECT_CREATE",d,"type="+a[2]+" scale="+scale);p.sendMessage(fmt.success("Scaled project created."));}catch(Exception e){p.sendMessage(fmt.error("Invalid project values."));} return true;} if(a[1].equalsIgnoreCase("support")){String project=a.length>2?a[2]:"all";String details=a.length>3?String.join(" ",java.util.Arrays.copyOfRange(a,3,a.length)):"Development materials and staffing requested";p.performCommand("civic support request "+project+" "+details);return true;} if(a[1].equalsIgnoreCase("contribute")){if(a.length<5){p.sendMessage(fmt.error("Usage: /district project contribute <id> <cash|items> <amount>"));return true;} try{contribute(p,d,Integer.parseInt(a[2]),a[3],Long.parseLong(a[4]));}catch(NumberFormatException e){p.sendMessage(fmt.error("Invalid contribution values."));}return true;} return false; }
    private void contribute(Player p,DistrictData.District d,int project,String kind,long amount){if(amount<=0||usedToday(p,d)>=playerCap(d)){p.sendMessage(fmt.error("Daily contribution cap reached or invalid amount."));return;} try{if(kind.equalsIgnoreCase("cash")){if(cash.getPlayerCashTotal(p.getUniqueId())<amount){p.sendMessage(fmt.error("Not enough physical cash."));return;} var withdrawn=cash.withdrawCash(p,amount); long got=withdrawn.stream().mapToLong(cash::getCashAmount).sum(); if(got<amount){cash.depositCash(p,withdrawn);p.sendMessage(fmt.error("Cash withdrawal failed."));return;} withdrawn.forEach(item -> cash.invalidateCash(item,"DISTRICT_PROJECT_CONTRIBUTION")); plugin.getDatabase().executeUpdate("UPDATE district_projects SET cash_contributed=cash_contributed+? WHERE id=? AND district_id=?",got,project,d.getId()); record(p,d,project,"ECONOMY","CASH",got);}else{Material m=p.getInventory().getItemInMainHand().getType();if(m.isAir()||p.getInventory().getItemInMainHand().getAmount()<amount){p.sendMessage(fmt.error("Hold enough materials in your main hand."));return;}p.getInventory().getItemInMainHand().setAmount((int)(p.getInventory().getItemInMainHand().getAmount()-amount));plugin.getDatabase().executeUpdate("UPDATE district_projects SET item_contributed=item_contributed+? WHERE id=? AND district_id=?",amount,project,d.getId());record(p,d,project,"INFRASTRUCTURE","ITEM:"+m.name(),amount);} plugin.getDatabase().executeUpdate("UPDATE district_projects SET status=CASE WHEN cash_contributed>=cash_required AND item_contributed>=item_required THEN 'READY_FOR_APPROVAL' ELSE status END WHERE id=?",project);p.sendMessage(fmt.success("Contribution recorded and audited."));}catch(Exception e){p.sendMessage(fmt.error("Contribution could not be recorded."));}}
    private void record(Player p,DistrictData.District d,int project,String category,String source,long amount)throws SQLException{long now=System.currentTimeMillis();plugin.getDatabase().executeUpdate("INSERT INTO district_development_contributions (district_id,project_id,player_uuid,category,source,amount,contributed_at,details) VALUES (?,?,?,?,?,?,?,?)",d.getId(),project,p.getUniqueId().toString(),category,source,amount,now,"");plugin.getDatabase().executeUpdate("INSERT INTO district_development (district_id,updated_at,maintenance_state) VALUES (?,?,?) ON CONFLICT(district_id) DO UPDATE SET "+category.toLowerCase()+"="+category.toLowerCase()+"+excluded.updated_at*0+?, updated_at=?, maintenance_state=?",d.getId(),now,dormant(d)?"NEGLECTED":"STABLE",amount,now,dormant(d)?"NEGLECTED":"STABLE");plugin.getDatabase().executeUpdate("UPDATE district_development SET level=CASE WHEN economy+infrastructure+security+community+trade_score+law_and_order+maintenance>=50000 THEN 6 WHEN economy+infrastructure+security+community+trade_score+law_and_order+maintenance>=25000 THEN 5 WHEN economy+infrastructure+security+community+trade_score+law_and_order+maintenance>=12000 THEN 4 WHEN economy+infrastructure+security+community+trade_score+law_and_order+maintenance>=6000 THEN 3 WHEN economy+infrastructure+security+community+trade_score+law_and_order+maintenance>=2500 THEN 2 WHEN economy+infrastructure+security+community+trade_score+law_and_order+maintenance>=800 THEN 1 ELSE 0 END WHERE district_id=?",d.getId());audit(p,"DEVELOPMENT_CONTRIBUTE",d,"project="+project+" source="+source+" amount="+amount);}
    private long usedToday(Player p,DistrictData.District d){if(plugin.getConfigManager().isStaffSandbox())return 0;try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement("SELECT IFNULL(SUM(amount),0) FROM district_development_contributions WHERE district_id=? AND player_uuid=? AND contributed_at>?")){s.setInt(1,d.getId());s.setString(2,p.getUniqueId().toString());s.setLong(3,System.currentTimeMillis()-86_400_000L);ResultSet r=s.executeQuery();return r.next()?r.getLong(1):0;}catch(Exception e){return DAILY_PLAYER_CAP;}}
    private void report(Player p,DistrictData.District d){try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement("SELECT * FROM district_development WHERE district_id=?")){s.setInt(1,d.getId());ResultSet r=s.executeQuery();p.sendMessage(fmt.header("Development: "+d.getName()));p.sendMessage(fmt.info("Active members: &e"+activeMembers(d)+" &7| Requirement scale: &e"+String.format("%.2f",requirementScale(d))+" &7| "+(dormant(d)?"&6DORMANT":"&aACTIVE")));if(r.next())p.sendMessage(fmt.info("Level: &e"+r.getInt("level")+" &7| Economy "+r.getInt("economy")+" | Infrastructure "+r.getInt("infrastructure")+" | Security "+r.getInt("security")));else p.sendMessage(fmt.info("Level: &e0 CAMP &7| No contributions yet."));}catch(Exception e){p.sendMessage(fmt.error("Development data unavailable."));}}
    private void projects(Player p,DistrictData.District d){p.sendMessage(fmt.header("Projects: "+d.getName()));try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement("SELECT * FROM district_projects WHERE district_id=? ORDER BY id DESC")){s.setInt(1,d.getId());ResultSet r=s.executeQuery();boolean any=false;while(r.next()){any=true;p.sendMessage(fmt.info("&e#"+r.getInt("id")+" &f"+r.getString("type")+" &7"+r.getString("status")+" cash "+r.getLong("cash_contributed")+"/"+r.getLong("cash_required")+" items "+r.getInt("item_contributed")+"/"+r.getInt("item_required")));}if(!any)p.sendMessage(fmt.info("No active projects."));}catch(Exception e){p.sendMessage(fmt.error("Projects unavailable."));}}
    private void projectInfo(Player p,DistrictData.District d,int id){try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement("SELECT * FROM district_projects WHERE id=? AND district_id=?")){s.setInt(1,id);s.setInt(2,d.getId());ResultSet r=s.executeQuery();if(!r.next()){p.sendMessage(fmt.error("Project not found."));return;}p.sendMessage(fmt.header("Project #"+id+": "+r.getString("type")));p.sendMessage(fmt.info("Status: &e"+r.getString("status")+" &7| Category: &e"+r.getString("category")));p.sendMessage(fmt.info("Cash: &6"+r.getLong("cash_contributed")+"/&6"+r.getLong("cash_required")+" &7| Items: &e"+r.getInt("item_contributed")+"/&e"+r.getInt("item_required")));}catch(Exception e){p.sendMessage(fmt.error("Project unavailable."));}}
    private void maintenance(Player p,DistrictData.District d){MaintenanceSnapshot snapshot=refreshMaintenance(d);p.sendMessage(fmt.header("Maintenance: "+d.getName()));String color=snapshot.state.equals("STABLE")?"&a":snapshot.state.equals("WARNING")?"&e":snapshot.state.equals("CRITICAL")?"&6":"&c";p.sendMessage(fmt.info("State: "+color+snapshot.state+" &7| Score: &e"+snapshot.score+"/100 &7| Active members: &e"+snapshot.activeMembers));p.sendMessage(fmt.info("30d contributions: &e"+snapshot.contributions+" &7| Open evidence: &e"+snapshot.openEvidence+" &7| Paused projects: &e"+snapshot.pausedProjects+" &7| Inactivity: &e"+snapshot.inactiveDays+"d"));if(snapshot.state.equals("WARNING"))p.sendMessage(fmt.warn("Maintenance is decaying. Contributions, active membership, and resolving evidence restore the score."));if(snapshot.state.equals("CRITICAL"))p.sendMessage(fmt.warn("Development is at risk. A SUSPENDED score blocks new upgrades."));if(snapshot.state.equals("SUSPENDED"))p.sendMessage(fmt.error("New upgrades are suspended. At most one stored development level can decay per seven days until recovery."));}
    private MaintenanceSnapshot refreshMaintenance(DistrictData.District d){long now=System.currentTimeMillis();int members=activeMembers(d);long contributions=scalar("SELECT COALESCE(SUM(amount),0) FROM district_development_contributions WHERE district_id=? AND contributed_at>=?",d.getId(),now-30L*86400000L);int evidence=(int)scalar("SELECT COUNT(*) FROM district_evidence WHERE district_id=? AND status IN ('UNHANDLED','ACTIVE')",d.getId());int paused=(int)scalar("SELECT COUNT(*) FROM district_projects WHERE district_id=? AND status IN ('PAUSED','READY_FOR_APPROVAL')",d.getId());long last=Math.max(scalar("SELECT COALESCE(MAX(contributed_at),0) FROM district_development_contributions WHERE district_id=?",d.getId()),d.getMembers().stream().mapToLong(id->Bukkit.getOfflinePlayer(id).getLastPlayed()).max().orElse(0));long inactiveDays=last<=0?30:Math.max(0,(now-last)/86400000L);int score=60+Math.min(20,members*5)+(int)Math.min(15,contributions/1000)+Math.min(5,(int)(d.getTreasuryBalance()/10000))-Math.min(30,evidence*3)-Math.min(20,paused*4)-(int)Math.min(40,Math.max(0,inactiveDays-3)*3);if(dormant(d))score-=15;score=Math.max(0,Math.min(100,score));String state=score>=70?"STABLE":score>=50?"WARNING":score>=30?"CRITICAL":"SUSPENDED";try{plugin.getDatabase().executeUpdate("INSERT INTO district_development(district_id,maintenance,maintenance_state,updated_at) VALUES(?,?,?,?) ON CONFLICT(district_id) DO UPDATE SET maintenance=excluded.maintenance,maintenance_state=excluded.maintenance_state,updated_at=excluded.updated_at",d.getId(),score,state,now);if(state.equals("SUSPENDED")&&inactiveDays>=30){long lastDowngrade=scalar("SELECT COALESCE(CAST(setting_value AS INTEGER),0) FROM district_settings WHERE district_id=? AND setting_key='maintenance_last_downgrade'",d.getId());if(now-lastDowngrade>=7L*86400000L){plugin.getDatabase().executeUpdate("UPDATE district_development SET level=MAX(0,level-1) WHERE district_id=? AND level>0",d.getId());plugin.getDatabase().executeUpdate("INSERT INTO district_settings(district_id,setting_key,setting_value) VALUES(?,'maintenance_last_downgrade',?) ON CONFLICT(district_id,setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_at=datetime('now')",d.getId(),String.valueOf(now));}}}catch(Exception ignored){}return new MaintenanceSnapshot(score,state,members,contributions,evidence,paused,inactiveDays);}
    private boolean maintenanceSuspended(DistrictData.District d){return "SUSPENDED".equals(refreshMaintenance(d).state);}
    private long scalar(String sql,Object... values){try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement(sql)){for(int i=0;i<values.length;i++)s.setObject(i+1,values[i]);ResultSet r=s.executeQuery();return r.next()?r.getLong(1):0;}catch(Exception e){return 0;}}
    private String text(String sql,Object... values){try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement(sql)){for(int i=0;i<values.length;i++)s.setObject(i+1,values[i]);ResultSet r=s.executeQuery();return r.next()?r.getString(1):"";}catch(Exception e){return "";}}
    private record MaintenanceSnapshot(int score,String state,int activeMembers,long contributions,int openEvidence,int pausedProjects,long inactiveDays){}
    private void contributors(Player p,DistrictData.District d){p.sendMessage(fmt.header("Top Contributors"));try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement("SELECT player_uuid,SUM(amount) total FROM district_development_contributions WHERE district_id=? GROUP BY player_uuid ORDER BY total DESC LIMIT 10")){s.setInt(1,d.getId());ResultSet r=s.executeQuery();while(r.next())p.sendMessage(fmt.info("&e"+r.getString("player_uuid")+" &7"+r.getLong("total")));}catch(Exception e){p.sendMessage(fmt.error("Contributors unavailable."));}}
    private int activeMembers(DistrictData.District d){return (int)d.getMembers().stream().filter(id -> Bukkit.getOfflinePlayer(id).getLastPlayed() > System.currentTimeMillis()-604800000L).count();}
    private double requirementScale(DistrictData.District d){if(plugin.getConfigManager().isStaffSandbox())return 1;int n=activeMembers(d); double scale=n<=3?.65:n<=8?1:n<=15?1.35:1.75; if(Bukkit.getOfflinePlayers().length<20)scale*=.70;return scale;}
    private long playerCap(DistrictData.District d){return plugin.getConfigManager().isStaffSandbox()?Long.MAX_VALUE:Math.max(1000,(long)(DAILY_PLAYER_CAP*Math.max(.35,requirementScale(d))));}
    private boolean dormant(DistrictData.District d){return !plugin.getConfigManager().isStaffSandbox()&&d.getMembers().stream().noneMatch(id -> Bukkit.getOfflinePlayer(id).getLastPlayed()>System.currentTimeMillis()-14L*86400000L);}
    private int parse(String raw){try{return Integer.parseInt(raw);}catch(Exception e){return -1;}}
    private String category(String t){return t.toUpperCase().contains("STATION")?"INFRASTRUCTURE":t.toUpperCase().contains("POLICE")?"SECURITY":"COMMUNITY";} private void audit(Player p,String action,DistrictData.District d,String detail){plugin.getAuditLogger().log(p.getUniqueId(),p.getName(),action,"DISTRICT",String.valueOf(d.getId()),detail);}
}
