package com.vaultsurvival.plugin.districts;

import com.vaultsurvival.plugin.VaultSurvivalPlugin;
import com.vaultsurvival.plugin.currency.CashPaymentService;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import java.sql.PreparedStatement;
import java.util.*;
import java.util.concurrent.*;

/** Individual 0-5 facility progression; no abstract infrastructure/trade/security scores. */
public final class DistrictFacilityService{
    public enum Facility{TOWN_HALL,MARKET,STATION,JAIL,FARM,AUCTION_HOUSE}
    public record State(Facility facility,int level,long nextCost,String benefit,boolean unlocked){}
    private final VaultSurvivalPlugin plugin;private final DistrictService districts;private final CashPaymentService payments;private final Map<Integer,EnumMap<Facility,Integer>> levels=new ConcurrentHashMap<>();
    public DistrictFacilityService(VaultSurvivalPlugin plugin,DistrictService districts){this.plugin=plugin;this.districts=districts;this.payments=plugin.getServiceRegistry().get(CashPaymentService.class);}
    public CompletableFuture<Void> load(){return plugin.getDatabase().read(c->{Map<Integer,EnumMap<Facility,Integer>> loaded=new HashMap<>();try(PreparedStatement p=c.prepareStatement("SELECT district_id,facility_type,level FROM district_facility_levels");var r=p.executeQuery()){while(r.next())loaded.computeIfAbsent(r.getInt(1),ignored->new EnumMap<>(Facility.class)).put(Facility.valueOf(r.getString(2)),r.getInt(3));}return loaded;}).thenAccept(loaded->{levels.clear();levels.putAll(loaded);});}
    public List<State> states(int districtId){int hall=level(districtId,Facility.TOWN_HALL);return Arrays.stream(Facility.values()).map(f->{int level=level(districtId,f);boolean unlocked=f!=Facility.AUCTION_HOUSE||hall>=5;return new State(f,level,level>=5?0:cost(f,level+1),benefit(f,level),unlocked);}).toList();}
    public int level(int districtId,Facility facility){return levels.getOrDefault(districtId,new EnumMap<>(Facility.class)).getOrDefault(facility,0);}
    public CompletableFuture<State> upgrade(Player actor,Facility facility){if(!Bukkit.isPrimaryThread())return CompletableFuture.failedFuture(new IllegalStateException("Facility upgrades must start on the main thread"));DistrictData.District district=districts.getPlayerDistrict(actor.getUniqueId());if(district==null||!(district.hasRole(actor.getUniqueId(),DistrictData.DistrictRole.MAYOR)||district.hasRole(actor.getUniqueId(),DistrictData.DistrictRole.CO_MAYOR)))return CompletableFuture.failedFuture(new SecurityException("Requires MAYOR or CO_MAYOR at the District Town Clerk"));int current=level(district.getId(),facility);if(current>=5)return CompletableFuture.failedFuture(new IllegalStateException("Facility is already level 5"));if(facility==Facility.AUCTION_HOUSE&&level(district.getId(),Facility.TOWN_HALL)<5)return CompletableFuture.failedFuture(new IllegalStateException("Town Hall level 5 is required to unlock the Auction House"));int next=current+1;long cost=cost(facility,next);String key="facility:"+district.getId()+":"+facility+":"+next;UUID actorId=actor.getUniqueId();String actorName=actor.getName();return payments.executeDistrictTreasury(actorId,district.getId(),cost,key,"DISTRICT_FACILITY",district.getId()+":"+facility,(c,plan)->{try(PreparedStatement p=c.prepareStatement("INSERT INTO district_facility_levels(district_id,facility_type,level,updated_at,updated_by,last_transaction_uuid) VALUES(?,?,?,?,?,?) ON CONFLICT(district_id,facility_type) DO UPDATE SET level=MAX(level,excluded.level),updated_at=excluded.updated_at,updated_by=excluded.updated_by,last_transaction_uuid=excluded.last_transaction_uuid")){p.setInt(1,district.getId());p.setString(2,facility.name());p.setInt(3,next);p.setLong(4,System.currentTimeMillis());p.setString(5,actorId.toString());p.setString(6,plan.transactionUuid().toString());p.executeUpdate();}}).thenApply(ignored->{levels.computeIfAbsent(district.getId(),id->new EnumMap<>(Facility.class)).put(facility,next);plugin.getAuditLogger().log(actorId,actorName,"DISTRICT_FACILITY_UPGRADE","DISTRICT",String.valueOf(district.getId()),"facility="+facility+" level="+next+" cost="+cost);return new State(facility,next,next>=5?0:cost(facility,next+1),benefit(facility,next),true);});}
    public long cost(Facility facility,int level){List<Long> defaults=List.of(5_000L,15_000L,40_000L,90_000L,180_000L);List<Long> configured=plugin.getConfigManager().getConfig().getLongList("districtFacilities."+facility.name().toLowerCase(Locale.ROOT)+".upgradeCosts");List<Long> values=configured.size()==5?configured:defaults;return values.get(Math.max(1,Math.min(5,level))-1);}
    public String benefit(Facility facility,int level){if(level<=0)return switch(facility){case TOWN_HALL->"Founding administration only";case MARKET->"No managed market bonuses";case STATION->"No district station upgrades";case JAIL->"No managed cells";case FARM->"No automated farm workers";case AUCTION_HOUSE->"Locked until Town Hall level 5";};return switch(facility){case TOWN_HALL->switch(level){case 1->"10 members and basic laws";case 2->"18 members and claim expansion";case 3->"30 members and two restricted areas";case 4->"45 members and advanced governance";default->"60 members and Auction House unlocked";};case MARKET->"+"+(level*2)+" merchant shop slots; "+Math.max(2,12-level*2)+"% market upkeep";case STATION->level+" route slot(s); boarding window bonus "+(level*15)+" seconds";case JAIL->level*2+" cells; evidence retention "+(7+level*3)+" days";case FARM->"District-wide farm automation level "+level;case AUCTION_HOUSE->level*10+" district listings; district receives "+(20+level*10)+"% of auction tax";};}
}
