package com.vaultsurvival.plugin.districts;

import com.vaultsurvival.plugin.VaultSurvivalPlugin;
import com.vaultsurvival.plugin.npc.NpcData;
import com.vaultsurvival.plugin.npc.NpcService;
import com.vaultsurvival.plugin.currency.CashPaymentService;
import org.bukkit.*;
import org.bukkit.block.Container;
import org.bukkit.block.data.Ageable;
import org.bukkit.entity.*;
import org.bukkit.inventory.ItemStack;
import org.bukkit.scheduler.BukkitTask;
import java.sql.PreparedStatement;
import java.util.*;
import java.util.concurrent.*;

public final class DistrictFarmService{
    public enum FarmType{CROPS,ANIMALS}
    public record FarmZone(String world,int minX,int minY,int minZ,int maxX,int maxY,int maxZ){public FarmZone{int a=minX,b=maxX;minX=Math.min(a,b);maxX=Math.max(a,b);a=minY;b=maxY;minY=Math.min(a,b);maxY=Math.max(a,b);a=minZ;b=maxZ;minZ=Math.min(a,b);maxZ=Math.max(a,b);}public boolean contains(int x,int y,int z){return x>=minX&&x<=maxX&&y>=minY&&y<=maxY&&z>=minZ&&z<=maxZ;}public double distanceSquared(Location l){double x=Math.max(minX,Math.min(maxX,l.getX())),y=Math.max(minY,Math.min(maxY,l.getY())),z=Math.max(minZ,Math.min(maxZ,l.getZ()));return l.distanceSquared(new Location(l.getWorld(),x,y,z));}}
    public static final class Farm{public final int id,districtId;public final String name;public final FarmType type;public final FarmZone zone;public volatile int level;public volatile String inputWorld,outputWorld;public volatile int inputX,inputY,inputZ,outputX,outputY,outputZ;public final Set<Integer> workerNpcIds=ConcurrentHashMap.newKeySet();public final Map<Integer,FarmZone> workerZones=new ConcurrentHashMap<>();Farm(int id,int districtId,String name,FarmType type,FarmZone zone,int level){this.id=id;this.districtId=districtId;this.name=name;this.type=type;this.zone=zone;this.level=level;}public boolean hasInput(){return inputWorld!=null;}public boolean hasOutput(){return outputWorld!=null;}}
    private final VaultSurvivalPlugin plugin;private final DistrictService districts;private final CashPaymentService payments;private final Map<Integer,Farm> farms=new ConcurrentHashMap<>();private BukkitTask task;
    public DistrictFarmService(VaultSurvivalPlugin plugin,DistrictService districts){this.plugin=plugin;this.districts=districts;this.payments=plugin.getServiceRegistry().get(CashPaymentService.class);}
    public CompletableFuture<Void> load(){return plugin.getDatabase().read(c->{Map<Integer,Farm> loaded=new HashMap<>();try(PreparedStatement p=c.prepareStatement("SELECT * FROM district_farms");var r=p.executeQuery()){while(r.next()){Farm farm=new Farm(r.getInt("id"),r.getInt("district_id"),r.getString("name"),FarmType.valueOf(r.getString("farm_type")),new FarmZone(r.getString("world"),r.getInt("min_x"),r.getInt("min_y"),r.getInt("min_z"),r.getInt("max_x"),r.getInt("max_y"),r.getInt("max_z")),r.getInt("level"));farm.inputWorld=r.getString("input_world");farm.inputX=r.getInt("input_x");farm.inputY=r.getInt("input_y");farm.inputZ=r.getInt("input_z");farm.outputWorld=r.getString("output_world");farm.outputX=r.getInt("output_x");farm.outputY=r.getInt("output_y");farm.outputZ=r.getInt("output_z");loaded.put(farm.id,farm);}}try(PreparedStatement p=c.prepareStatement("SELECT * FROM district_farm_workers WHERE status='ACTIVE'");var r=p.executeQuery()){while(r.next()){Farm farm=loaded.get(r.getInt("farm_id"));if(farm!=null){int npc=r.getInt("npc_id");farm.workerNpcIds.add(npc);String world=r.getString("work_world");farm.workerZones.put(npc,world==null?farm.zone:new FarmZone(world,r.getInt("min_x"),r.getInt("min_y"),r.getInt("min_z"),r.getInt("max_x"),r.getInt("max_y"),r.getInt("max_z")));}}}return loaded;}).thenAccept(loaded->{farms.clear();farms.putAll(loaded);});}
    public void start(){if(task!=null)return;long ticks=Math.max(20,plugin.getConfigManager().getConfig().getLong("districtFarms.worker.intervalTicks",1200));task=Bukkit.getScheduler().runTaskTimer(plugin,this::tick,ticks,ticks);}
    public void stop(){if(task!=null)task.cancel();task=null;}
    public List<Farm> farms(int districtId){return farms.values().stream().filter(f->f.districtId==districtId).sorted(Comparator.comparingInt(f->f.id)).toList();}
    public Farm get(int id){return farms.get(id);}
    public CompletableFuture<Farm> create(Player actor,String name,FarmType type,FarmZone zone){DistrictData.District district=authorized(actor);DistrictData.BlockClaim claim=districts.getClaim(district.getId());if(claim==null||!claim.worldName().equals(zone.world())||!claim.contains(zone.minX(),zone.minZ())||!claim.contains(zone.maxX(),zone.maxZ()))return CompletableFuture.failedFuture(new IllegalStateException("The complete farm zone must be inside the district claim"));String safeName=DistrictFarmRules.validateName(name);DistrictFarmRules.requireAllowedFootprint(zone,claim,plugin.getConfigManager().getConfig().getDouble("districtFarms.maxPercentOfDistrict",0.25D));int maximum=Math.max(1,plugin.getConfigManager().getConfig().getInt("districtFarms.maxFarmsPerDistrict",8));if(farms(district.getId()).size()>=maximum)return CompletableFuture.failedFuture(new IllegalStateException("District farm limit reached"));UUID actorId=actor.getUniqueId();String actorName=actor.getName();return plugin.getDatabase().write(c->{try(PreparedStatement p=c.prepareStatement("INSERT INTO district_farms(district_id,name,farm_type,world,min_x,min_y,min_z,max_x,max_y,max_z,level,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,1,?,?)",java.sql.Statement.RETURN_GENERATED_KEYS)){p.setInt(1,district.getId());p.setString(2,safeName);p.setString(3,type.name());p.setString(4,zone.world());p.setInt(5,zone.minX());p.setInt(6,zone.minY());p.setInt(7,zone.minZ());p.setInt(8,zone.maxX());p.setInt(9,zone.maxY());p.setInt(10,zone.maxZ());p.setString(11,actorId.toString());p.setLong(12,System.currentTimeMillis());p.executeUpdate();try(var keys=p.getGeneratedKeys()){if(!keys.next())throw new IllegalStateException("No farm id generated");return new Farm(keys.getInt(1),district.getId(),safeName,type,zone,1);}}}).thenApply(f->{farms.put(f.id,f);plugin.getAuditLogger().log(actorId,actorName,"DISTRICT_FARM_CREATE","DISTRICT",String.valueOf(district.getId()),"farm="+f.id+" type="+type);return f;});}
    public CompletableFuture<Farm> setOutput(Player actor,int farmId,org.bukkit.block.Block block){Farm farm=requiredFarm(actor,farmId);if(!(block.getState() instanceof Container))return CompletableFuture.failedFuture(new IllegalArgumentException("Select a chest, barrel, or other container"));double max=Math.max(1,plugin.getConfigManager().getConfig().getDouble("districtFarms.outputChest.maxDistanceBlocks",16));Location location=block.getLocation();if(!farm.zone.world().equals(location.getWorld().getName())||farm.zone.distanceSquared(location)>max*max)return CompletableFuture.failedFuture(new IllegalStateException("Output container must be within "+max+" blocks of the farm zone"));return plugin.getDatabase().write(c->{try(PreparedStatement p=c.prepareStatement("UPDATE district_farms SET output_world=?,output_x=?,output_y=?,output_z=? WHERE id=?")){p.setString(1,location.getWorld().getName());p.setInt(2,location.getBlockX());p.setInt(3,location.getBlockY());p.setInt(4,location.getBlockZ());p.setInt(5,farm.id);p.executeUpdate();}return null;}).thenApply(v->{farm.outputWorld=location.getWorld().getName();farm.outputX=location.getBlockX();farm.outputY=location.getBlockY();farm.outputZ=location.getBlockZ();return farm;});}
    public CompletableFuture<Farm> setInput(Player actor,int farmId,org.bukkit.block.Block block){Farm farm=requiredFarm(actor,farmId);if(!(block.getState() instanceof Container))return CompletableFuture.failedFuture(new IllegalArgumentException("Select a chest, barrel, or other container"));double max=Math.max(1,plugin.getConfigManager().getConfig().getDouble("districtFarms.inputChest.maxDistanceBlocks",16));Location location=block.getLocation();if(!farm.zone.world().equals(location.getWorld().getName())||farm.zone.distanceSquared(location)>max*max)return CompletableFuture.failedFuture(new IllegalStateException("Input container must be within "+max+" blocks of the farm zone"));return plugin.getDatabase().write(c->{try(PreparedStatement p=c.prepareStatement("UPDATE district_farms SET input_world=?,input_x=?,input_y=?,input_z=? WHERE id=?")){p.setString(1,location.getWorld().getName());p.setInt(2,location.getBlockX());p.setInt(3,location.getBlockY());p.setInt(4,location.getBlockZ());p.setInt(5,farm.id);p.executeUpdate();}return null;}).thenApply(v->{farm.inputWorld=location.getWorld().getName();farm.inputX=location.getBlockX();farm.inputY=location.getBlockY();farm.inputZ=location.getBlockZ();return farm;});}
    public CompletableFuture<Integer> placeWorker(Player actor,int farmId,FarmZone workZone,Location location,String skin){Farm farm=requiredFarm(actor,farmId);if(!farm.zone.world().equals(workZone.world())||!farm.zone.contains(workZone.minX(),workZone.minY(),workZone.minZ())||!farm.zone.contains(workZone.maxX(),workZone.maxY(),workZone.maxZ()))return CompletableFuture.failedFuture(new IllegalArgumentException("Worker surface must be completely inside the mayor-designated farm zone"));int level=effectiveLevel(farm);if(level<=0)return CompletableFuture.failedFuture(new IllegalStateException("Upgrade the district Farm facility to level 1 first"));if(farm.workerNpcIds.size()>=maxWorkers(level))return CompletableFuture.failedFuture(new IllegalStateException("District farm level "+level+" allows "+maxWorkers(level)+" worker NPC(s) per zone"));double max=Math.max(1,plugin.getConfigManager().getConfig().getDouble("districtFarms.worker.maxDistanceFromFarmBlocks",8));if(!farm.zone.world().equals(location.getWorld().getName())||workZone.distanceSquared(location)>max*max)return CompletableFuture.failedFuture(new IllegalStateException("Worker must be within "+max+" blocks of its selected work surface"));NpcData.Npc npc=plugin.getServiceRegistry().get(NpcService.class).createNpc(farm.name+" Farm Worker",skin,location,NpcData.ActionType.NONE,"FARM:"+farm.id);if(npc==null)return CompletableFuture.failedFuture(new IllegalStateException("Worker NPC could not be created"));return plugin.getDatabase().write(c->{try(PreparedStatement p=c.prepareStatement("INSERT INTO district_farm_workers(farm_id,npc_id,placed_by,placed_at,status,work_world,min_x,min_y,min_z,max_x,max_y,max_z) VALUES(?,?,?,?,'ACTIVE',?,?,?,?,?,?,?)")){p.setInt(1,farm.id);p.setInt(2,npc.getId());p.setString(3,actor.getUniqueId().toString());p.setLong(4,System.currentTimeMillis());p.setString(5,workZone.world());p.setInt(6,workZone.minX());p.setInt(7,workZone.minY());p.setInt(8,workZone.minZ());p.setInt(9,workZone.maxX());p.setInt(10,workZone.maxY());p.setInt(11,workZone.maxZ());p.executeUpdate();}return npc.getId();}).thenApply(id->{farm.workerNpcIds.add(id);farm.workerZones.put(id,workZone);return id;});}
    private DistrictData.District authorized(Player actor){DistrictData.District district=districts.getPlayerDistrict(actor.getUniqueId());if(district==null||!(district.hasRole(actor.getUniqueId(),DistrictData.DistrictRole.FARMER)||district.hasRole(actor.getUniqueId(),DistrictData.DistrictRole.MAYOR)||district.hasRole(actor.getUniqueId(),DistrictData.DistrictRole.CO_MAYOR)))throw new SecurityException("Requires FARMER, MAYOR, or CO_MAYOR");return district;}
    private Farm requiredFarm(Player actor,int id){DistrictData.District district=authorized(actor);Farm farm=farms.get(id);if(farm==null||farm.districtId!=district.getId())throw new IllegalArgumentException("Farm not found in your district");return farm;}
    private int effectiveLevel(Farm farm){return plugin.getServiceRegistry().get(DistrictFacilityService.class).level(farm.districtId,DistrictFacilityService.Facility.FARM);}
    private int maxWorkers(int level){return DistrictFarmRules.levelValue(plugin.getConfigManager().getConfig().getIntegerList("districtFarms.levels.maxWorkers"),level,1);}
    private int outputCap(int level){return DistrictFarmRules.levelValue(plugin.getConfigManager().getConfig().getIntegerList("districtFarms.levels.maxOutputPerWorkerInterval"),level,64);}
    private void tick(){NpcService npcs=plugin.getServiceRegistry().get(NpcService.class);double max=Math.max(1,plugin.getConfigManager().getConfig().getDouble("districtFarms.worker.maxDistanceFromFarmBlocks",8));for(Farm farm:farms.values())if(farm.hasOutput()&&effectiveLevel(farm)>0)for(int npcId:farm.workerNpcIds){NpcData.Npc npc=npcs.getNpc(npcId);Location location=npc==null?null:npc.getLocation();FarmZone work=farm.workerZones.getOrDefault(npcId,farm.zone);if(location==null||!work.world().equals(location.getWorld().getName())||work.distanceSquared(location)>max*max)continue;int cap=outputCap(effectiveLevel(farm));if(farm.type==FarmType.CROPS)maintainCrops(farm,work,cap);else maintainAnimals(farm,work,cap);}}
    private Container output(Farm farm){World world=Bukkit.getWorld(farm.outputWorld);if(world==null||!world.isChunkLoaded(farm.outputX>>4,farm.outputZ>>4))return null;return world.getBlockAt(farm.outputX,farm.outputY,farm.outputZ).getState() instanceof Container c?c:null;}
    private Container input(Farm farm){World world=Bukkit.getWorld(farm.inputWorld);if(world==null||!world.isChunkLoaded(farm.inputX>>4,farm.inputZ>>4))return null;return world.getBlockAt(farm.inputX,farm.inputY,farm.inputZ).getState() instanceof Container c?c:null;}
    private void maintainCrops(Farm farm,FarmZone work,int cap){World world=Bukkit.getWorld(work.world());Container output=output(farm);if(world==null||output==null)return;int produced=0,scanned=0,maxScan=Math.max(100,plugin.getConfigManager().getConfig().getInt("districtFarms.worker.maxBlocksScannedPerInterval",4096));outer:for(int y=work.minY();y<=work.maxY();y++)for(int x=work.minX();x<=work.maxX();x++)for(int z=work.minZ();z<=work.maxZ();z++){if(++scanned>maxScan||produced>=cap)break outer;if(!world.isChunkLoaded(x>>4,z>>4))continue;var block=world.getBlockAt(x,y,z);if(!(block.getBlockData() instanceof Ageable age)||age.getAge()<age.getMaximumAge())continue;Collection<ItemStack> drops=block.getDrops();int amount=drops.stream().mapToInt(ItemStack::getAmount).sum();if(amount==0||produced+amount>cap||!canFit(output,drops))continue;output.getInventory().addItem(drops.toArray(ItemStack[]::new));age.setAge(0);block.setBlockData(age,false);produced+=amount;}}
    private void maintainAnimals(Farm farm,FarmZone work,int cap){World world=Bukkit.getWorld(work.world());Container output=output(farm);int centerX=(work.minX()+work.maxX())/2,centerZ=(work.minZ()+work.maxZ())/2;if(world==null||output==null||!world.isChunkLoaded(centerX>>4,centerZ>>4))return;int reserve=Math.max(2,plugin.getConfigManager().getConfig().getInt("districtFarms.animals.minimumAdultsPerSpecies",4)),produced=0;Map<Class<?>,List<Animals>> species=new HashMap<>();for(Entity entity:world.getNearbyEntities(new Location(world,centerX,(work.minY()+work.maxY())/2d,centerZ),(work.maxX()-work.minX()+1)/2d,(work.maxY()-work.minY()+1)/2d,(work.maxZ()-work.minZ()+1)/2d)){if(entity instanceof Animals animal&&animal.isAdult()&&work.contains(entity.getLocation().getBlockX(),entity.getLocation().getBlockY(),entity.getLocation().getBlockZ()))species.computeIfAbsent(entity.getClass(),k->new ArrayList<>()).add(animal);}breedFromInput(farm,species);for(List<Animals> adults:species.values())while(adults.size()>reserve&&produced<cap){Animals animal=adults.removeLast();List<ItemStack> drops=animalDrops(animal);int amount=drops.stream().mapToInt(ItemStack::getAmount).sum();if(drops.isEmpty()||produced+amount>cap||!canFit(output,drops))break;output.getInventory().addItem(drops.toArray(ItemStack[]::new));animal.remove();produced+=amount;}}
    private void breedFromInput(Farm farm,Map<Class<?>,List<Animals>> species){Container input=input(farm);if(input==null)return;Material feed=Material.matchMaterial(plugin.getConfigManager().getConfig().getString("districtFarms.animals.breedingItem","WHEAT"));int cost=Math.max(2,plugin.getConfigManager().getConfig().getInt("districtFarms.animals.breedingItemPerPair",2));if(feed==null)return;for(List<Animals> adults:species.values()){List<Animals> ready=adults.stream().filter(Animals::canBreed).limit(2).toList();if(ready.size()<2||!removeMaterial(input,feed,cost))continue;ready.forEach(animal->animal.setLoveModeTicks(600));}}
    private boolean removeMaterial(Container container,Material material,int amount){int available=Arrays.stream(container.getInventory().getStorageContents()).filter(Objects::nonNull).filter(item->item.getType()==material).mapToInt(ItemStack::getAmount).sum();if(available<amount)return false;int remaining=amount;for(ItemStack item:container.getInventory().getStorageContents())if(item!=null&&item.getType()==material){int take=Math.min(remaining,item.getAmount());item.setAmount(item.getAmount()-take);remaining-=take;if(remaining==0)return true;}return true;}
    private boolean canFit(Container container,Collection<ItemStack> additions){ItemStack[] simulated=Arrays.stream(container.getInventory().getStorageContents()).map(item->item==null?null:item.clone()).toArray(ItemStack[]::new);for(ItemStack addition:additions){int remaining=addition.getAmount();for(ItemStack slot:simulated)if(slot!=null&&slot.isSimilar(addition)){int moved=Math.min(remaining,slot.getMaxStackSize()-slot.getAmount());slot.setAmount(slot.getAmount()+moved);remaining-=moved;if(remaining==0)break;}while(remaining>0){int empty=-1;for(int i=0;i<simulated.length;i++)if(simulated[i]==null||simulated[i].getType().isAir()){empty=i;break;}if(empty<0)return false;ItemStack stack=addition.clone();stack.setAmount(Math.min(remaining,stack.getMaxStackSize()));simulated[empty]=stack;remaining-=stack.getAmount();}}return true;}
    private List<ItemStack> animalDrops(Animals animal){if(animal instanceof Cow)return List.of(new ItemStack(Material.BEEF,2),new ItemStack(Material.LEATHER));if(animal instanceof Pig)return List.of(new ItemStack(Material.PORKCHOP,2));if(animal instanceof Sheep sheep)return List.of(new ItemStack(Material.MUTTON,2),new ItemStack(Material.valueOf(sheep.getColor().name()+"_WOOL")));if(animal instanceof Chicken)return List.of(new ItemStack(Material.CHICKEN),new ItemStack(Material.FEATHER,2));if(animal instanceof Rabbit)return List.of(new ItemStack(Material.RABBIT),new ItemStack(Material.RABBIT_HIDE));return List.of();}
}
