package com.vaultsurvival.plugin.districts;

import com.vaultsurvival.plugin.VaultSurvivalPlugin;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;
import java.util.*;
import java.util.concurrent.CompletableFuture;

public final class DistrictFoundingService{
    private final VaultSurvivalPlugin plugin;private final DistrictFoundingRepository repository;private final DistrictFoundingValidationService validation;private final NamespacedKey contractKey;
    public DistrictFoundingService(VaultSurvivalPlugin plugin,DistrictFoundingRepository repository,DistrictFoundingValidationService validation){this.plugin=plugin;this.repository=repository;this.validation=validation;this.contractKey=new NamespacedKey(plugin,"district_independence_contract");}
    public CompletableFuture<DistrictFoundingPetition> create(Player founder,String name){assertMain();validation.validateNewFounder(founder.getUniqueId(),name);long days=Math.max(1,plugin.getConfigManager().getConfig().getLong("districts.founding.petitionExpiryDays",7));String idempotency="founding:create:"+founder.getUniqueId()+":"+name.toLowerCase(Locale.ROOT);return repository.create(founder.getUniqueId(),name.trim(),System.currentTimeMillis()+days*86_400_000L,idempotency).thenApply(p->{audit(founder,"DISTRICT_FOUNDING_CREATE",p.petitionUuid(),"name="+p.districtName());return p;});}
    public CompletableFuture<DistrictFoundingPetition> current(UUID founder){return repository.byFounder(founder).thenApply(o->o.orElse(null));}
    public CompletableFuture<List<DistrictFoundingPetition>> invitations(UUID player){return repository.invitations(player);}
    public CompletableFuture<DistrictFoundingPetition> invite(Player founder,String playerName,DistrictData.DistrictRole role){assertMain();Player invited=Bukkit.getPlayerExact(playerName);if(invited==null)throw new IllegalArgumentException("Invited player must be online for UUID-safe selection");validation.validateInvite(invited.getUniqueId());if(role==DistrictData.DistrictRole.MAYOR||role==DistrictData.DistrictRole.VISITOR)role=DistrictData.DistrictRole.MEMBER;DistrictData.DistrictRole selected=role;return repository.byFounder(founder.getUniqueId()).thenCompose(o->{DistrictFoundingPetition p=o.orElseThrow(()->new IllegalStateException("Create a petition first"));return repository.invite(p.petitionUuid(),founder.getUniqueId(),invited.getUniqueId(),selected);}).thenApply(p->{audit(founder,"DISTRICT_FOUNDING_INVITE",p.petitionUuid(),"player="+invited.getUniqueId()+" role="+selected);return p;});}
    public CompletableFuture<DistrictFoundingPetition> respond(Player player,UUID petition,boolean accept){assertMain();if(accept)validation.validateInvite(player.getUniqueId());return repository.respond(petition,player.getUniqueId(),accept).thenApply(p->{audit(player,accept?"DISTRICT_FOUNDING_ACCEPT":"DISTRICT_FOUNDING_DECLINE",petition,"");return p;});}
    public CompletableFuture<DistrictFoundingPetition> attachClaim(Player founder,UUID petition,DistrictData.BlockClaim claim){assertMain();validation.validateClaim(claim);UUID contract=UUID.randomUUID();return repository.attachClaim(petition,founder.getUniqueId(),claim,contract).thenApply(p->{Bukkit.getScheduler().runTask(plugin,()->{if(founder.isOnline()){founder.getInventory().addItem(contract(p)).values().forEach(left->founder.getWorld().dropItemNaturally(founder.getLocation(),left));founder.sendMessage(plugin.getMessageFormatter().success("Claim attached. Return this signed independence contract to the Spawn City Town Clerk."));}});audit(founder,"DISTRICT_FOUNDING_CLAIM",petition,"area="+claim.areaBlocks());return p;});}
    public void startClaim(Player founder){assertMain();repository.byFounder(founder.getUniqueId()).whenComplete((found,failure)->Bukkit.getScheduler().runTask(plugin,()->{if(failure!=null||found.isEmpty()){founder.sendMessage(plugin.getMessageFormatter().error("No active founding petition."));return;}DistrictFoundingPetition p=found.get();if(p.acceptedCount()<3){founder.sendMessage(plugin.getMessageFormatter().error("Three accepted unique founders are required before selecting land."));return;}plugin.getServiceRegistry().get(DistrictSelectionService.class).startFounding(p.petitionUuid(),p.districtName(),founder);}));}
    public CompletableFuture<DistrictFoundingRepository.Submitted> submit(Player founder){assertMain();ItemStack contract=findContract(founder);if(contract==null)return CompletableFuture.failedFuture(new IllegalStateException("Bring the matching independence contract back to the Town Clerk"));UUID petition=UUID.fromString(contract.getItemMeta().getPersistentDataContainer().get(contractKey,PersistentDataType.STRING));return repository.byFounder(founder.getUniqueId()).thenCompose(o->{DistrictFoundingPetition p=o.orElseThrow(()->new IllegalStateException("No active petition"));if(!p.petitionUuid().equals(petition)||p.contractUuid()==null)throw new IllegalStateException("This contract does not match the active petition");for(var participant:p.participants().values())if(participant.status()==DistrictFoundingPetition.ParticipantStatus.ACCEPTED)validation.validateInviteForSubmission(participant.playerUuid(),founder.getUniqueId());return repository.submit(petition,founder.getUniqueId());}).thenApply(submitted->{Bukkit.getScheduler().runTask(plugin,()->{removeContract(founder,petition);if(plugin.getServiceRegistry().get(DistrictService.class) instanceof DistrictServiceImpl impl)impl.registerFoundingApplication(submitted.districtId(),submitted.petition());founder.sendMessage(plugin.getMessageFormatter().success("District application submitted for staff review."));});audit(founder,"DISTRICT_FOUNDING_SUBMIT",petition,"district="+submitted.districtId());return submitted;});}
    public boolean isContract(ItemStack item){return item!=null&&item.hasItemMeta()&&item.getItemMeta().getPersistentDataContainer().has(contractKey,PersistentDataType.STRING);}
    private ItemStack contract(DistrictFoundingPetition p){ItemStack item=new ItemStack(Material.PAPER);ItemMeta meta=item.getItemMeta();meta.displayName(plugin.getMessageFormatter().deserialize("&f&lContract of Independence"));meta.lore(List.of(plugin.getMessageFormatter().deserialize("&7District: &e"+p.districtName()),plugin.getMessageFormatter().deserialize("&7Accepted founders: &e"+p.acceptedCount()),plugin.getMessageFormatter().deserialize("&8Contract: "+p.contractUuid())));meta.getPersistentDataContainer().set(contractKey,PersistentDataType.STRING,p.petitionUuid().toString());item.setItemMeta(meta);return item;}
    private ItemStack findContract(Player player){for(ItemStack item:player.getInventory().getStorageContents())if(isContract(item))return item;return null;}
    private void removeContract(Player player,UUID petition){for(int i=0;i<player.getInventory().getStorageContents().length;i++){ItemStack item=player.getInventory().getItem(i);if(isContract(item)&&petition.toString().equals(item.getItemMeta().getPersistentDataContainer().get(contractKey,PersistentDataType.STRING))){player.getInventory().setItem(i,null);return;}}}
    private void audit(Player actor,String action,UUID petition,String details){plugin.getAuditLogger().log(actor.getUniqueId(),actor.getName(),action,"DISTRICT_FOUNDING",petition.toString(),details);}
    private void assertMain(){if(!Bukkit.isPrimaryThread())throw new IllegalStateException("Founding Bukkit state must be captured on the main thread");}
}
