package com.vaultsurvival.plugin.districts;

import com.vaultsurvival.plugin.VaultSurvivalPlugin;
import com.vaultsurvival.plugin.core.MessageFormatter;
import com.vaultsurvival.plugin.currency.CurrencyService;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import java.sql.*;
import java.util.List;

/** Persistent, capped district contribution and project foundation. */
public final class DistrictDevelopmentService {
    private static final long DAILY_PLAYER_CAP = 10_000;
    private final VaultSurvivalPlugin plugin; private final DistrictService districts; private final CurrencyService cash; private final MessageFormatter fmt;
    public DistrictDevelopmentService(VaultSurvivalPlugin plugin) { this.plugin=plugin; districts=plugin.getServiceRegistry().get(DistrictService.class); cash=plugin.getServiceRegistry().get(CurrencyService.class); fmt=plugin.getMessageFormatter(); }
    public boolean handle(Player player, String command, String[] args) {
        DistrictData.District district=districts.getPlayerDistrict(player.getUniqueId());
        if(district==null){ player.sendMessage(fmt.error("You are not in a district.")); return true; }
        return switch(command){ case "development" -> { report(player,district); yield true; } case "projects" -> { projects(player,district); yield true; } case "maintenance" -> { maintenance(player,district); yield true; } case "contributors" -> { contributors(player,district); yield true; } case "project" -> project(player,district,args); default -> false; };
    }
    private boolean project(Player p,DistrictData.District d,String[] a){ if(a.length<2){p.sendMessage(fmt.error("Usage: /district project <create|contribute> ..."));return true;} if(a[1].equalsIgnoreCase("create")){if(!districts.canManageDevelopment(p.getUniqueId(),d)){p.sendMessage(fmt.permissionDenied());return true;} if(a.length<5){p.sendMessage(fmt.error("Usage: /district project create <type> <cashRequired> <itemsRequired>"));return true;} try{plugin.getDatabase().executeUpdate("INSERT INTO district_projects (district_id,type,category,status,cash_required,item_required,created_by,created_at) VALUES (?,?,?,'ACTIVE',?,?,?,?)",d.getId(),a[2],category(a[2]),Long.parseLong(a[3]),Integer.parseInt(a[4]),p.getUniqueId().toString(),System.currentTimeMillis()); audit(p,"PROJECT_CREATE",d,"type="+a[2]);p.sendMessage(fmt.success("Project created."));}catch(Exception e){p.sendMessage(fmt.error("Invalid project values."));} return true;} if(a[1].equalsIgnoreCase("contribute")){if(a.length<5){p.sendMessage(fmt.error("Usage: /district project contribute <id> <cash|items> <amount>"));return true;} try{contribute(p,d,Integer.parseInt(a[2]),a[3],Long.parseLong(a[4]));}catch(NumberFormatException e){p.sendMessage(fmt.error("Invalid contribution values."));}return true;} return false; }
    private void contribute(Player p,DistrictData.District d,int project,String kind,long amount){if(amount<=0||usedToday(p,d)>=DAILY_PLAYER_CAP){p.sendMessage(fmt.error("Daily contribution cap reached or invalid amount."));return;} try{if(kind.equalsIgnoreCase("cash")){if(cash.getPlayerCashTotal(p.getUniqueId())<amount){p.sendMessage(fmt.error("Not enough physical cash."));return;} long got=cash.withdrawCash(p,amount).stream().mapToLong(cash::getCashAmount).sum(); if(got<amount){p.sendMessage(fmt.error("Cash withdrawal failed."));return;} plugin.getDatabase().executeUpdate("UPDATE district_projects SET cash_contributed=cash_contributed+? WHERE id=? AND district_id=?",got,project,d.getId()); record(p,d,project,"ECONOMY","CASH",got);}else{Material m=p.getInventory().getItemInMainHand().getType();if(m.isAir()||p.getInventory().getItemInMainHand().getAmount()<amount){p.sendMessage(fmt.error("Hold enough materials in your main hand."));return;}p.getInventory().getItemInMainHand().setAmount((int)(p.getInventory().getItemInMainHand().getAmount()-amount));plugin.getDatabase().executeUpdate("UPDATE district_projects SET item_contributed=item_contributed+? WHERE id=? AND district_id=?",amount,project,d.getId());record(p,d,project,"INFRASTRUCTURE","ITEM:"+m.name(),amount);} plugin.getDatabase().executeUpdate("UPDATE district_projects SET status=CASE WHEN cash_contributed>=cash_required AND item_contributed>=item_required THEN 'READY_FOR_APPROVAL' ELSE status END WHERE id=?",project);p.sendMessage(fmt.success("Contribution recorded and audited."));}catch(Exception e){p.sendMessage(fmt.error("Contribution could not be recorded."));}}
    private void record(Player p,DistrictData.District d,int project,String category,String source,long amount)throws SQLException{long now=System.currentTimeMillis();plugin.getDatabase().executeUpdate("INSERT INTO district_development_contributions (district_id,project_id,player_uuid,category,source,amount,contributed_at,details) VALUES (?,?,?,?,?,?,?,?)",d.getId(),project,p.getUniqueId().toString(),category,source,amount,now,"");plugin.getDatabase().executeUpdate("INSERT INTO district_development (district_id,updated_at) VALUES (?,?) ON CONFLICT(district_id) DO UPDATE SET "+category.toLowerCase()+"="+category.toLowerCase()+"+excluded.updated_at*0+?, updated_at=?",d.getId(),now,amount,now);audit(p,"DEVELOPMENT_CONTRIBUTE",d,"project="+project+" source="+source+" amount="+amount);}
    private long usedToday(Player p,DistrictData.District d){try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement("SELECT IFNULL(SUM(amount),0) FROM district_development_contributions WHERE district_id=? AND player_uuid=? AND contributed_at>?")){s.setInt(1,d.getId());s.setString(2,p.getUniqueId().toString());s.setLong(3,System.currentTimeMillis()-86_400_000L);ResultSet r=s.executeQuery();return r.next()?r.getLong(1):0;}catch(Exception e){return DAILY_PLAYER_CAP;}}
    private void report(Player p,DistrictData.District d){try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement("SELECT * FROM district_development WHERE district_id=?")){s.setInt(1,d.getId());ResultSet r=s.executeQuery();p.sendMessage(fmt.header("Development: "+d.getName()));if(r.next())p.sendMessage(fmt.info("Level: &e"+r.getInt("level")+" &7| Economy "+r.getInt("economy")+" | Infrastructure "+r.getInt("infrastructure")+" | Security "+r.getInt("security")));else p.sendMessage(fmt.info("Level: &e0 CAMP &7| No contributions yet."));}catch(Exception e){p.sendMessage(fmt.error("Development data unavailable."));}}
    private void projects(Player p,DistrictData.District d){p.sendMessage(fmt.header("Projects: "+d.getName()));try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement("SELECT * FROM district_projects WHERE district_id=? ORDER BY id DESC")){s.setInt(1,d.getId());ResultSet r=s.executeQuery();boolean any=false;while(r.next()){any=true;p.sendMessage(fmt.info("&e#"+r.getInt("id")+" &f"+r.getString("type")+" &7"+r.getString("status")+" cash "+r.getLong("cash_contributed")+"/"+r.getLong("cash_required")+" items "+r.getInt("item_contributed")+"/"+r.getInt("item_required")));}if(!any)p.sendMessage(fmt.info("No active projects."));}catch(Exception e){p.sendMessage(fmt.error("Projects unavailable."));}}
    private void maintenance(Player p,DistrictData.District d){p.sendMessage(fmt.header("Maintenance: "+d.getName()));p.sendMessage(fmt.info("State: &aSTABLE &7until maintenance scoring is configured. Warnings and suspension will precede any downgrade; stored value is never deleted."));}
    private void contributors(Player p,DistrictData.District d){p.sendMessage(fmt.header("Top Contributors"));try(Connection c=plugin.getDatabase().getConnection();PreparedStatement s=c.prepareStatement("SELECT player_uuid,SUM(amount) total FROM district_development_contributions WHERE district_id=? GROUP BY player_uuid ORDER BY total DESC LIMIT 10")){s.setInt(1,d.getId());ResultSet r=s.executeQuery();while(r.next())p.sendMessage(fmt.info("&e"+r.getString("player_uuid")+" &7"+r.getLong("total")));}catch(Exception e){p.sendMessage(fmt.error("Contributors unavailable."));}}
    private String category(String t){return t.toUpperCase().contains("STATION")?"INFRASTRUCTURE":t.toUpperCase().contains("POLICE")?"SECURITY":"COMMUNITY";} private void audit(Player p,String action,DistrictData.District d,String detail){plugin.getAuditLogger().log(p.getUniqueId(),p.getName(),action,"DISTRICT",String.valueOf(d.getId()),detail);}
}
