package com.vaultsurvival.plugin.districts;

import com.vaultsurvival.plugin.VaultSurvivalPlugin;
import java.util.UUID;

public final class DistrictFoundingValidationService{
    private final VaultSurvivalPlugin plugin;private final DistrictService districts;
    public DistrictFoundingValidationService(VaultSurvivalPlugin plugin,DistrictService districts){this.plugin=plugin;this.districts=districts;}
    public void validateNewFounder(UUID founder,String name){if(name==null||!name.matches("[A-Za-z0-9 _-]{3,32}"))throw new IllegalArgumentException("District name must be 3-32 readable characters");if(districts.getPlayerDistrict(founder)!=null)throw new IllegalStateException("You already belong to a district");if(districts.getAllDistricts().stream().anyMatch(d->d.getStatus()!=DistrictData.DistrictStatus.DISBANDED&&d.getName().equalsIgnoreCase(name)))throw new IllegalStateException("That district name is already used");}
    public void validateInvite(UUID invited){if(districts.getPlayerDistrict(invited)!=null)throw new IllegalStateException("That player already belongs to a district");}
    public void validateInviteForSubmission(UUID invited,UUID founder){DistrictData.District current=districts.getPlayerDistrict(invited);if(current!=null)throw new IllegalStateException((invited.equals(founder)?"Founder":"An accepted founder")+" already belongs to another district");}
    public void validateClaim(DistrictData.BlockClaim claim){long min=plugin.getConfigManager().getConfig().getLong("districts.selection.requiredAreaBlocks",2500),max=plugin.getConfigManager().getDistrictInitialClaimBlocks();if(claim==null||claim.areaBlocks()<min||claim.areaBlocks()>max)throw new IllegalStateException("Claim must contain between "+min+" and "+max+" blocks");var spawnService=plugin.getServiceRegistry().get(com.vaultsurvival.plugin.spawncity.SpawnCityService.class);var spawn=spawnService.getSpawnLocation();if(spawn!=null&&spawn.getWorld().getName().equals(claim.worldName())&&distanceToClaim(spawn.getBlockX(),spawn.getBlockZ(),claim)<plugin.getConfigManager().getDistrictMinDistanceFromSpawn())throw new IllegalStateException("Claim is too close to "+spawnService.getCityName());int required=plugin.getConfigManager().getDistrictMinDistanceBetween();for(var district:districts.getAllDistricts()){if(district.getStatus()==DistrictData.DistrictStatus.DISBANDED||!district.getWorldName().equals(claim.worldName()))continue;DistrictData.BlockClaim other=districts.getClaim(district.getId());double distance=other==null?Math.hypot(claim.centerBlockX()-district.getCenterX(),claim.centerBlockZ()-district.getCenterZ()):distanceBetween(claim,other);if(distance<required)throw new IllegalStateException("Claim is too close to district "+district.getName());}}
    private static double distanceToClaim(int x,int z,DistrictData.BlockClaim claim){int nearestX=Math.max(claim.minBlockX(),Math.min(x,claim.maxBlockX())),nearestZ=Math.max(claim.minBlockZ(),Math.min(z,claim.maxBlockZ()));return Math.hypot(x-nearestX,z-nearestZ);}
    private static double distanceBetween(DistrictData.BlockClaim a,DistrictData.BlockClaim b){int dx=Math.max(0,Math.max(a.minBlockX()-b.maxBlockX(),b.minBlockX()-a.maxBlockX())),dz=Math.max(0,Math.max(a.minBlockZ()-b.maxBlockZ(),b.minBlockZ()-a.maxBlockZ()));return Math.hypot(dx,dz);}
}
